### ISSUE TITLE
Unable to generate trends because I don't see the history folder

### ISSUE THREAD

**Issue by yeikel** [allure-framework/allure-maven#125]
#### I'm submitting a ... 
  - [x] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
I believe that `history` generation is missing. I read the docs and configured the plugin to use but I did not see any documentation explaining how to generate the `history` folder using this plugin. All the documentation that I read so far mentions that the history folder will be at the `allure-results` folder but I don't see such folder to generate the trends. 

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

```
<plugin>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-maven</artifactId>
                <version>2.7</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.20</version>
                <configuration>
                    <systemPropertyVariables>
                        <allure.results.directory>target/allure-results</allure.results.directory>
                    </systemPropertyVariables>
                    <testFailureIgnore>false</testFailureIgnore>
                    <argLine>
                        ${surefireArgLine} -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                    </argLine>
                    <properties>
                        <property>
                            <name>listener</name>
                            <value>io.qameta.allure.junit4.AllureJunit4</value>
                        </property>
                    </properties>
                </configuration>
            </plugin>
```

Steps 

1. `mvn clean test`
2. `mvn allure:report`

Expected : There is a folder called `history` inside `allure-results` that can be used for future builds

Actual : I do not see any history folder and thus I can't generate trends

#### What is the expected behavior?
I expect to see an `history` folder to be able to generate history with subsequent builds.

#### Please tell us about your environment:

- Test framework:      Junit
- Allure adaptor:        allure-junit4@2.13.2
- Generate report using: allure-maven@2.7

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by ismailazerty** [comment]
You should upgrade your allure maven plugin to 2.10.0.

**Comment by yeikel** [comment]
Closing. History is in the `site` after the report generation

**Comment by yeikel** [comment]
@ismailazerty I can't upgrade because it is quarantined by our internal repository
