### ISSUE TITLE
Release 2.11.0 not on Maven Central

### ISSUE THREAD

**Issue by TobiX** [allure-framework/allure-maven#219]
HI,

it seems the release 2.11.0 didn't make it to Maven Central: https://repo1.maven.org/maven2/io/qameta/allure/allure-maven/ ...

**Comment by baev** [comment]
confirmed, the issue is with missed checksums for sources and javadoc jars, that's why it got rejected by Maven Central

**Comment by TobiX** [comment]
Since 2.11.2 is on central, this is fixed for me.
