### ISSUE TITLE
Reports works in Intellij and not in eclipse

### ISSUE THREAD

**Issue by Siva2221** [allure-framework/allure-maven#225]
Issue
I'm using Allure+Maven+Testng for report in my framework.

When I run maven goal command "mvn clean test site" test is running and reports are generated in site folder.

Problem is when I open the report in Intellij it redirects to http://localhost:port url and reports are loaded as expected. But when I open the report in eclipse the reports are loading with local system directory URL and report page shows as loading. Also getting 404 Not found error.

What is the difference here ? I'm surprised that reports are working fine in Intellij and not working in Eclipse.

Any suggestion or help on this ?

Refer screenshot attached 
![tempsnip_Intellij](https://user-images.githubusercontent.com/22488701/151804852-bb9ec5f1-2173-421a-8ba9-06183f97fcad.png)

![tempsnip_eclipse](https://user-images.githubusercontent.com/22488701/151804879-2a36c17c-92d2-40a5-bc0d-38054337b73f.png)

![tempsnip_404NotFound](https://user-images.githubusercontent.com/22488701/151805317-33a66644-0f64-4c01-9035-28df509d5ecb.png)

**Comment by Siva2221** [comment]
Issue is not specific in chrome. Report is not opening in any browsers when I open from eclipse.

In Intellij report is opening in all browsers.

**Comment by baev** [comment]
> Issue is not specific to chrome

it's more like webkit specific, not chrome. 

> In Intellij report is opening in all browsers.

That's because Intellij starts webserver when opens html page and eclipse don't. Allure provides `open` and `serve` commands.
