### ISSUE TITLE
Hi , I have a doubt due to which i am stuck long time on my project . I have upgraded my project to jdk17 and after that allure has stopped working

### ISSUE THREAD

**Issue by vishvv01** [allure-framework/allure-maven#278]
Can you please help me find the issue in my pom.xml due to which allure is not gettin genrated from maven? 

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>myproj</groupId>
  <artifactId>myproj</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
  <name>myproj</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	  <aspectj.version>1.9.7</aspectj.version>
	  <suiteFile>${project.basedir}/TPSAPIs/TestSuiteFiles/MasterSuite.xml</suiteFile>
	  <environment>QA2</environment>
	  <allure.version>2.7.0</allure.version>
	  <allure.results.directory>${project.basedir}/target/allure-results</allure.results.directory>
	  <allure.report.directory>${project.basedir}/target/allure-report</allure.report.directory>
  </properties>
  
  

  
  
  
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<source>17</source>
					<target>17</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M7</version>
				<configuration>
					<testFailureIgnore>true</testFailureIgnore>
					<forkCount>0</forkCount>
				<argLine>
						-javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
					</argLine>
					<suiteXmlFiles>
						<suiteXmlFile>${suiteFile}</suiteXmlFile>
					</suiteXmlFiles>
					<properties>
                    <property>
                        <name>listener</name>
                        <value>ru.yandex.qatools.allure.testng.AllureTestListener</value>
                    </property>
                </properties>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.aspectj</groupId>
						<artifactId>aspectjweaver</artifactId>
						<version>1.9.7</version>
					</dependency>
				</dependencies>
			</plugin>
		
       
            <plugin>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-maven</artifactId>
                <version>2.12.0</version>
                <configuration>
                    <reportVersion>2.20.1</reportVersion>
                    <allureDownloadUrl>https://github.com/allure-framework/allure2/releases/download/2.20.1/allure-2.20.1.zip</allureDownloadUrl>
                     <resultsDirectory>${project.basedir}/target/allure-results</resultsDirectory>
                    <reportDirectory>${project.basedir}/target/allure-report</reportDirectory>
                </configuration>
            </plugin>
      
			
		</plugins>
	</build>

	<packaging>jar</packaging>
	
	
	  <dependencies>
	  
    <dependency>
        <groupId>ru.yandex.qatools.allure</groupId>
        <artifactId>allure-testng-adaptor</artifactId>
        <version>1.5.4</version>
    </dependency>

    	<dependency>
			<groupId>com.jayway.jsonpath</groupId>
			<artifactId>json-path</artifactId>
			<version>2.4.0</version>
		</dependency>
    <dependency>
		<groupId>io.rest-assured</groupId>
		<artifactId>rest-assured</artifactId>
		<version>4.3.0</version>
	</dependency>
	<dependency>
		<groupId>org.testng</groupId>
		<artifactId>testng</artifactId>
		<version>7.6.1</version>
	</dependency>
	<dependency>
    	<groupId>org.json</groupId>
    	<artifactId>json</artifactId>
    	<version>20180813</version>
  </dependency>
	  <dependency>
		  <groupId>com.opencsv</groupId>
		  <artifactId>opencsv</artifactId>
		  <version>4.6</version>
	  </dependency>
  <dependency>
    	<groupId>com.google.code.gson</groupId>
    	<artifactId>gson</artifactId>
    	<version>2.8.5</version>
  </dependency>
  <dependency>
    	<groupId>com.fasterxml.jackson.core</groupId>
    	<artifactId>jackson-databind</artifactId>
    	<version>2.14.0</version>
  </dependency>
  <dependency>
    <groupId>commons-beanutils</groupId>
    <artifactId>commons-beanutils</artifactId>
    <version>1.9.4</version>
</dependency>
  
  <dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>4.1.0</version>
		</dependency>
	  <dependency>
		  <groupId>io.qameta.allure</groupId>
		  <artifactId>allure-testng</artifactId>
		  <version>2.20.1</version>
		  <scope>test</scope>
	  </dependency>

 <dependency>
		  <groupId>com.myproj.foundation</groupId>
		  <artifactId>foundation</artifactId>
		  <version>1.0</version>
		  <scope>system</scope>
		  <systemPath>${project.basedir}/lib/foundation.jar</systemPath>
	  </dependency>
	
	  <dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>3.141.59</version>
		</dependency>
	  <dependency>
		  <groupId>org.jsoup</groupId>
		  <artifactId>jsoup</artifactId>
		  <version>1.13.1</version>
	  </dependency>
	  
		  <dependency>
		  <groupId>ru.yandex.qatools.allure</groupId>
		  <artifactId>allure-java-adaptor-api</artifactId>
		  <version>1.5.4</version>
		  <scope>compile</scope>
	  </dependency>
	 
	 
  </dependencies>

</project>

**Comment by baev** [comment]
closed as duplicate https://github.com/orgs/allure-framework/discussions/1835
