### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by etki** [allure-framework/allure-maven#28]
Current link in readme points to non-existing (probably just moved) jenkins build

**Comment by vania-pooh** [comment]
Any PR is welcome. :)

**Comment by etki** [comment]
@vania-pooh had no time yesterday #29

**Comment by etki** [comment]
@vania-pooh by the way, what is aqua branch for?

**Comment by vania-pooh** [comment]
Summon @eroshenkoam.
@etki seems to be an outdated internal stuff not for public usage. :)
