### ISSUE TITLE
allure.results.directory path setup

### ISSUE THREAD

**Issue by flynet** [allure-framework/allure-maven#30]
Sorry, I can't figure out how to set custom allure.results.directory, 

I have 
<allure.results.directory>target_${id}/allure-results_${id}</allure.results.directory>

but results goes to target/allure-results folder. 

How can I set this path ?

Also tried 
        resultsDirectory>target_${id}/allure-results_${id}</resultsDirectory
        inputDirectories>target_${id}/allure-results_${id}/allure-report</inputDirectories
didn't help

**Comment by baev** [comment]
You need to configure results directory to your adaptor. So you need to provide such property to `surefire` plugin. See http://maven.apache.org/surefire/maven-surefire-plugin/examples/system-properties.html

**Comment by flynet** [comment]
thanks for quick reply, It works.

**Comment by baev** [comment]
@flynet you are welcome
