### ISSUE TITLE
Allure2 report differs depending if report is generated by allure-maven plugin or by Allure CLI 

### ISSUE THREAD

**Issue by jaheikki** [allure-framework/allure-maven#43]
I'm submitting a bug report. The outputted Allure report differs depending if report is generated by   allure-maven plugin or by Allure CLI, even if the allure results are the same. I'm expecting the report generated by allure-maven plugin would be the same compared to report run by Allure CLI.

The report outputted from allure-maven plugin (mvn allure:report) seems to be incorrect (missing fields/information). 

See screenshot:

![image](https://user-images.githubusercontent.com/8567508/28816108-436b45f0-76ac-11e7-8b05-919661f6540c.png)

The report outputted from Allure CLI seems to be correct

allure generate -c  /Users/heikmjar/git/tietoallas/citest/target/allure-results -o /Users/heikmjar/git/tietoallas/citest/target/myreport

See screenshot from Allure CLI run in Mac OS X:
![image](https://user-images.githubusercontent.com/8567508/28815813-49946714-76ab-11e7-90cf-88724ed70745.png)

Environment:
- Allure version:        2.0.1
- Test framework:        Cucumber JVM
- Allure adaptor:        allure-cucumber-jvm 2.0-BETA16
- Generate report using: io.qameta.allure/allure-maven@2.8 

Additional information:
Command I used to generate results (json): mvn clean install -Dcucumber.options="--plugin io.qameta.allure.cucumberjvm.AllureCucumberJvm --tags @caresuite"

Clip from pom.xml: 
<dependency>
         <groupId>io.qameta.allure</groupId>
         <artifactId>allure-cucumber-jvm</artifactId>
         <version>2.0-BETA16</version>
     </dependency>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.20</version>
                <configuration>
                    <argLine>
                        -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                         -Dcucumber.options="--plugin io.qameta.allure.cucumberjvm.AllureCucumberJvm"
                    </argLine>
                    <systemPropertyVariables>
                        <allure.results.directory>target/allure-results</allure.results.directory>
                    </systemPropertyVariables>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
            </plugin>

            <plugin>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-maven</artifactId>
                <version>2.8</version>
                <configuration>
                    <reportVersion>2.0.1</reportVersion>
                    <resultsDirectory>allure-results</resultsDirectory>
                </configuration>
            </plugin>
        </plugins>
    </build>

Jaris-MacBook-Pro-2:citest heikmjar$ mvn allure:report
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building HUS CI tests 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- allure-maven:2.8:report (default-cli) @ hus-ci-tests ---
[INFO] Allure installation directory /Users/heikmjar/git/tietoallas/citest/.allure
[INFO] Try to finding out allure 2.0.1
[INFO] Generate Allure report (report) with version 2.0.1
[INFO] Generate Allure report to /Users/heikmjar/git/tietoallas/citest/target/site/allure-maven-plugin
[INFO] Found results directory /Users/heikmjar/git/tietoallas/citest/target/allure-results
[INFO] Can't find information about categories.
[INFO] Generate report to /Users/heikmjar/git/tietoallas/citest/target/site/allure-maven-plugin
Report successfully generated to /Users/heikmjar/git/tietoallas/citest/target/site/allure-maven-plugin
[INFO] Report generated successfully.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.043 s
[INFO] Finished at: 2017-08-01T10:53:10+03:00
[INFO] Final Memory: 17M/309M

**Comment by eroshenkoam** [comment]
Seems like you have different versions of allure cli local and in maven report. 
You can easily configure allure report version in maven plugin like here: 
```
<plugin>
    <groupId>io.qameta.allure</groupId>
    <artifactId>allure-maven</artifactId>
    <version>2.8</version>
    <configuration>
        <reportVersion>2.3.1</reportVersion>
    </configuration>
</plugin>
```

**Comment by jaheikki** [comment]
Ok, setting this reportVersion to latest version seems to solve the problem. You can close this issue, thanks!

**Comment by mesonjesi** [comment]
Hi I have the same problem

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>selenium-cucumber-java</groupId>
  <artifactId>selenium-cucumber-java</artifactId>
  <version>1.0.1-SNAPSHOT</version>

	<dependencies>
		
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>1.2.5</version>
		</dependency>

		
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>1.2.5</version>
		</dependency>

		
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>

		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.12.0</version>
		</dependency>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>3.12.0</version>
		</dependency>

		
		<dependency>
		    <groupId>io.appium</groupId>
		    <artifactId>java-client</artifactId>
		    <version>5.0.4</version>
		</dependency>

		
		<dependency>
            <groupId>ru.yandex.qatools.allure</groupId>
            <artifactId>allure-cucumber-jvm-adaptor</artifactId>
            <version>1.6.4</version>
        </dependency>

        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
	</dependencies>

	
	<properties>
    	<aspectj.version>1.8.11</aspectj.version>
    	<slf4j.version>1.7.21</slf4j.version>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.2</version>
				<configuration>
					<encoding>UTF-8</encoding>
					<source>1.8</source>
					<target>1.8</target>
					<compilerArgument>-Werror</compilerArgument>
					<systemPropertyVariables>
						<property>
							<name>browser</name>
							<value>${browser}</value>
						</property>
						<property>
							<name>cloud_config</name>
							<value>${cloud_config}</value>
						</property>
					</systemPropertyVariables>
				</configuration>
			</plugin>

			
			<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.21.0</version>
                <configuration>
                    <testFailureIgnore>false</testFailureIgnore>
                   <argLine>
                        -javaagent:${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar
                        -Dcucumber.options="--plugin ru.yandex.qatools.allure.cucumberjvm.AllureReporter"
                    </argLine>
                </configuration>
                <dependencies>
					<dependency>
						<groupId>org.aspectj</groupId>
						<artifactId>aspectjweaver</artifactId>
						<version>${aspectj.version}</version>
					</dependency>
                </dependencies>
            </plugin>
			<plugin>
				<groupId>io.qameta.allure</groupId>
				<artifactId>allure-maven</artifactId>
				<version>2.8</version>
				<configuration>
					<reportVersion>2.3.1</reportVersion>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>




[INFO] Allure installation directory C:\selenium-cucumber-java/.allure
[INFO] Try to finding out allure 2.3.1
[INFO] Generate Allure report (serve) with version 2.3.1
[INFO] Generate Allure report to C:\selenium-cucumber-java\target\site/allure-maven-plugin
[INFO] Found results directory C:\selenium-cucumber-java\target\allure-results
[INFO] Can't find information about categories.
[INFO] Generate report to C:\selenium-cucumber-java\target\site\allure-maven-plugin
Generating report to temp directory...
send analytics
Report successfully generated to C:\Users\U186185\AppData\Local\Temp\2884065329970993727\allure-report
Starting web server...
2019-05-10 16:56:50.156:INFO::main: Logging initialized @4480ms
Server started at <http://192.168.51.175:60232/>. Press <Ctrl+C> to exit
