### ISSUE TITLE
Add support for configuring path to categories.json file

### ISSUE THREAD

**Issue by aiannucci** [allure-framework/allure-maven#46]
#### I'm submitting a ... 
  - [ ] bug report
  - [X] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

When you want to use custom categories in your report, you need to somehow manually copy a categories.json file into your allure-results folder, which requires the use of some other plugin or script in our CI environment.

#### What is the expected behavior?

Include a configuration in the Allure Maven plugin to specify the path to your categories.json file, so the same plugin can take care of placing it in the allure-results folder, just before generating the report.

#### What is the motivation / use case for changing the behavior?

With this configuration, you wouldn't need for a custom process, another Maven plugin or a script to copy the file for you.

#### Please tell us about your environment:

- Allure version:        2.3.1
- Test framework:        junit4@4.12
- Allure adaptor:        allure-junit4@2.0-BETA16
- Generate report using: allure-maven@2.8

**Comment by eroshenkoam** [comment]
@aiannucci just try to copy categories.json file into resources directory

**Comment by eroshenkoam** [comment]
we are already read `categories.json` from test resources: 
https://github.com/allure-framework/allure-maven/blob/master/src/main/java/io/qameta/allure/maven/AllureGenerateMojo.java#L138
