### ISSUE TITLE
To short timeout for generateReport method.

### ISSUE THREAD

**Issue by Coder1304** [allure-framework/allure-maven#59]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**.
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository . to create an issue: https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jenkinsci_allure-2Dplugin_issues&d=DwID-g&c=FXJfUb1oWgygD0uNz-ujnA&r=0UmIrFabaQzxDSWUHSk4XGdSmWxwvG6dNIPErIqoA5w&m=Zk5f8fr-juxF9Wf6APpHK9wfIi4U6IWjAGkBMDwNxsY&s=-jDADsxOnLlZN00vHyYmwMmPaF6fVD-7aZdoIkbNPsU&e=
.
. Make sure you have a clear name for your issue. The name should start with a capital . letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins . - Support emoji in test descriptions
)

#### I'm submitting a ...
  * [x] bug report
  * [ ] feature request
  * [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
For large amount of test results, allure framework generates report longer than 60 sec which cause timeout of ExecuteWatchdog. Allure framework process is killed and report is only partially generated. Exception is thrown:

[ERROR] Can't generate allure report data
org.apache.commons.exec.ExecuteException: Process exited with an error: 143 (Exit value: 143)

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. 
To reproduce the bug you have to generate large amount of data for allure framework. For example: web application tests which stores each send and received messages.

#### What is the expected behavior?
Timeout for AllureCommandline::generateReport should be configurable just like in case of AllureCommandline::serve.

#### What is the motivation / use case for changing the behavior?
Fix the malfunction of the main functionality.

#### Please tell us about your environment:

- Allure version:        2.7.0
- Test framework:        testng@6.14.3
- Allure adaptor:        allure-testng@2.6.0
- Generate report using: allure-maven@2.9
- Apache Maven     3.3.9
- maven-surefire-plugin    2.21.0

#### Other information

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions . how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
@korobochka could you please submit a pull request with the fix?

**Comment by korobochka** [comment]
Do you want the timeout to be separate from `serveTimeout`? I think it does not really make sense to have two, I'd rename `serveTimeout` -> `timeout` and use it for both `generate` and `serve`.

**Comment by Coder1304** [comment]
@korobochka I am OK with that. This will require update of configuration for `serve` users but I think it's low cost.

**Comment by Coder1304** [comment]
@korobochka This solution is OK for me, I am not using `serv` in my project, so backward compatibility is not so important for me.
