### ISSUE TITLE
Unable to Generate the Allure report

### ISSUE THREAD

**Issue by SubbuLomada** [allure-framework/allure-maven#72]
Error: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project allure-testng-example: Error during page generation: Error rendering Maven report: Could not generate the report: InvocationTargetException: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) Error injecting constructor, java.lang.NoClassDefFoundError: javax/xml/bind/ValidationEventLocator
[ERROR]   at ru.yandex.qatools.allure.data.converters.DefaultTestCaseConverter.<init>(DefaultTestCaseConverter.groovy:35)
[ERROR]   while locating ru.yandex.qatools.allure.data.converters.DefaultTestCaseConverter
[ERROR]   while locating ru.yandex.qatools.allure.data.converters.TestCaseConverter
[ERROR]     for field at ru.yandex.qatools.allure.data.AllureReportGenerator.converter(AllureReportGenerator.java:37)
[ERROR]   while locating ru.yandex.qatools.allure.data.AllureReportGenerator
[ERROR] 
[ERROR] 1 error: javax.xml.bind.ValidationEventLocator
[ERROR] -> [Help 1]

XML: <?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ru.yandex.qatools.allure</groupId>
        <artifactId>allure-examples-parent</artifactId>
        <version>1.0</version>
    </parent> 

    <artifactId>allure-testng-example</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <allure.version>1.5.4</allure.version>
        <aspectj.version>1.9.2</aspectj.version>
      <suiteXmlFile>Executer.xml</suiteXmlFile>      
    </properties>

    <name>Testing</name>
    <description>Testing application</description>
    
     <repositories>
		<repository>
			<id>central</id>
			<name>Repo1</name>
			<url>http://repo1.maven.org/maven2</url>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>false</enabled>
				<updatePolicy>never</updatePolicy>
			</snapshots>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>central</id>
			<name>Repo1</name>
			<url>http://repo1.maven.org/maven2</url>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>false</enabled>
				<updatePolicy>never</updatePolicy>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

    <dependencies>
        <dependency>
            <groupId>ru.yandex.qatools.allure</groupId>
            <artifactId>allure-testng-adaptor</artifactId>
            <version>${allure.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        
	  <dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
        

        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>1.3</version>
        </dependency>
        
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.11</version>
		</dependency>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.14.3</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>dom4j</groupId>
			<artifactId>dom4j</artifactId>
			<version>1.6.1</version>
		</dependency>
		<dependency>
			<groupId>jaxen</groupId>
			<artifactId>jaxen</artifactId>
			<version>1.1.6</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.4</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.4</version>
		</dependency>
	 	<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.1.3</version>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-core</artifactId>
			<version>1.1.3</version>
		</dependency>  
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.12</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-api</artifactId>
			<version>3.141.59</version>
			
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-support</artifactId>
			<version>3.141.59</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-remote-driver</artifactId>
			<version>3.141.59</version>
		</dependency>
		<dependency>
		    <groupId>org.seleniumhq.selenium</groupId>
		    <artifactId>selenium-chrome-driver</artifactId>
		    <version>3.141.59</version>
		</dependency>
		<dependency>
			<groupId>org.apache.xmlbeans</groupId>
			<artifactId>xmlbeans</artifactId>
			<version>3.0.2</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.xmlbeans</groupId>
			<artifactId>xmlbeans-xmlpublic</artifactId>
			<version>2.6.0</version>
		</dependency>
		<dependency>
    <groupId>ru.yandex.qatools.allure</groupId>
    <artifactId>allure-java-adaptor-api</artifactId>
    <version>1.5.4</version>
</dependency>
		<dependency>
		  <groupId>com.codoid.products</groupId>
		  <artifactId>fillo</artifactId>
		  <version>1.18</version>
		</dependency>	
		<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.1</version>
</dependency>

<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-core</artifactId>
    <version>2.3.0.1</version>
</dependency>
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-impl</artifactId>
    <version>2.3.2</version>
</dependency>
<dependency>
    <groupId>javax.activation</groupId>
    <artifactId>activation</artifactId>
    <version>1.1.1</version>
</dependency>	
    </dependencies>

 	<organization>
        <name>Yandex</name>
        <url>http://company.yandex.com</url>
    </organization>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <url>https://github.com/allure-framework/allure-maven-plugin</url>
        <connection>scm:git@github.com:allure-framework/allure-maven-plugin.git</connection>
        <developerConnection>scm:git:git@github.com:allure-framework/allure-maven-plugin.git</developerConnection>
    </scm>

    <issueManagement>
        <system>GitHub Issues</system>
        <url>https://github.com/allure-framework/allure-maven-plugin/issues</url>
    </issueManagement>

    <ciManagement>
        <system>TeamCity</system>
        <url>http://teamcity.qatools.ru/</url>
    </ciManagement>

    <mailingLists>
        <mailingList>
            <name>Allure Mailing List</name>
            <post>allure@yandex-team.ru</post>
        </mailingList>
    </mailingLists>

    <prerequisites>
        <maven>3.3.3</maven>
    </prerequisites>
    

    <build>
    
      <resources>
			<resource>
				<directory>src/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources> 
		
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                
          			
        
                <testFailureIgnore>true</testFailureIgnore>
                    <argLine>
                        -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                    </argLine>
                   
                 
                 
							<forkMode>always</forkMode>
		        			<systemPropertyVariables>
		          			  <reporter.debug>false</reporter.debug>
		       				 </systemPropertyVariables>
						     <suiteXmlFiles>
						        <suiteXmlFile>${suiteXmlFile}</suiteXmlFile>
						     </suiteXmlFiles> 
					
                    
                </configuration>
               
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
            </plugin>

            
            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>9.2.10.v20150310</version>
                <configuration>
                    <webAppSourceDirectory>${project.build.directory}/site/allure-maven-plugin</webAppSourceDirectory>
                    <stopKey>stop</stopKey>
                    <stopPort>1234</stopPort>
                </configuration>
            </plugin>
        </plugins>
        	
    </build>

    <reporting>
        <excludeDefaults>true</excludeDefaults>
        <plugins>
            <plugin>
                <groupId>ru.yandex.qatools.allure</groupId>
                <artifactId>allure-maven-plugin</artifactId>
                <version>2.6</version>
            </plugin>
        </plugins>
    </reporting>

</project>

**Comment by SubbuLomada** [comment]
I am using Java 11

**Comment by baev** [comment]
Allure supports Java 11 since 2.9.0 release. Try to upgrade to the latest version (2.10.0) and everything should be fine

**Comment by SubbuLomada** [comment]
But we don't have 2.10 with this. if i upgrade the only allure will it work
<dependency>
            <groupId>ru.yandex.qatools.allure</groupId>
            <artifactId>allure-testng-adaptor</artifactId>
            <version>${allure.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by baev** [comment]
Allure 1 is reached EOF (all artefacts with `ru.yandex.qatools.allure` groupId). I'm not sure will that work with Java 11 or not.  **I would recommend you to upgrade to the latest versions** (`io.qameta.allure:allure-testng:2.10.0` at the moment)


As you are getting error during report generation you can try to only update Allure report generator. To do so you need to replace old `allure-maven-plugin` with a new one:

```xml
<plugin>
    <groupId>io.qameta.allure</groupId>
    <artifactId>allure-maven</artifactId>
    <version>2.10.0</version>
    <configuration>
        <reportVersion>2.10.0</reportVersion>
    </configuration>
</plugin>
```

**Comment by SubbuLomada** [comment]
@baev Thanks . It's working fine after upgrade

**Comment by Amrkamel1** [comment]
hi @baev 
everything was working fine until i upgrade some plugins version here is my POM that was working fine below, issue now that im unable to see allure-results or allure-report folder 
 
and whenever im running 
mvn clean
mvn site
mvn test 
i didnt get allure-report folder in target as before it was working fine 

   here is the POM 
   <?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>MobileAutomationTest</groupId>
    <artifactId>App</artifactId>
    <version>1.0-SNAPSHOT</version>


    <properties>
        <jre.level>1.8</jre.level>
        <jdk.level>1.8</jdk.level>
        <aspectj.version>1.9.5</aspectj.version>
    </properties>

    <build>
        <plugins>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${jdk.level}</source>
                    <target>${jdk.level}</target>
                </configuration>
            </plugin>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M4</version>
                <configuration>
                    <testFailureIgnore>true</testFailureIgnore>
                    <argLine>
                        -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                    </argLine>
                    <suiteXmlFiles>
                        <suiteXmlFile>src/test/java/TestNG.xml/</suiteXmlFile>
                    </suiteXmlFiles>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.1.0</version>
        </dependency>






        
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-server</artifactId>
            <version>3.141.59</version>
        </dependency>
        
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>7.3.0</version>
        </dependency>
        
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>com.relevantcodes</groupId>
            <artifactId>extentreports</artifactId>
            <version>2.41.2</version>
        </dependency>
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.29</version>
        </dependency>
    </dependencies>
    <reporting>
        <excludeDefaults>true</excludeDefaults>
        <plugins>
            <plugin>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-maven</artifactId>
                <version>2.10.0</version>
                <configuration>
                    <reportDirectory>${basedir}\target\allure-report</reportDirectory>
                </configuration>
            </plugin>
        </plugins>
    </reporting>

</project>


![image](https://user-images.githubusercontent.com/32042806/74574991-abcffa00-4f85-11ea-9c2a-8a644f54fb0d.png)
