### ISSUE TITLE
Is there anyway that we can customize Allure report. 

### ISSUE THREAD

**Issue by SubbuLomada** [allure-framework/allure-maven#73]
![Allure_Report](https://user-images.githubusercontent.com/48588427/55050879-f8ae9780-5078-11e9-94df-c962989e3b24.png)
[//]

**Comment by SubbuLomada** [comment]
Can we change the "test case" name to something like Scenario or something else... in the report

**Comment by SubbuLomada** [comment]
@baev Is there any way that we can customize the allure report

**Comment by baev** [comment]
@SubbuLomada the only way to change entity names in UI is create your own translation by forking allure report. 

See https://github.com/allure-framework/allure2/tree/master/allure-generator/src/main/javascript/translations
